import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter/foundation.dart';

/// Represents a single caption cue with timing.
class CaptionCue {
  final Duration start;
  final Duration end;
  final String text;

  const CaptionCue({
    required this.start,
    required this.end,
    required this.text,
  });
}

/// Represents an available caption track.
class CaptionTrack {
  final String languageCode;
  final String name;
  final String baseUrl;
  final bool isAutoGenerated;

  const CaptionTrack({
    required this.languageCode,
    required this.name,
    required this.baseUrl,
    this.isAutoGenerated = false,
  });
}

/// Service to fetch and parse YouTube captions/subtitles.
class CaptionService {
  static final http.Client _http = http.Client();

  /// Fetch available caption tracks for a video.
  static Future<List<CaptionTrack>> getTracks(String videoId) async {
    try {
      final uri = Uri.parse(
        'https://www.youtube.com/watch?v=$videoId',
      );
      final res = await _http.get(uri, headers: {
        'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
      }).timeout(const Duration(seconds: 10));

      if (res.statusCode != 200) return [];

      final body = res.body;
      final tracks = <CaptionTrack>[];

      // Extract captions data from ytInitialPlayerResponse
      final playerResponse = _extractJson(body, 'ytInitialPlayerResponse');
      if (playerResponse == null) return [];

      final captions = playerResponse['captions'];
      if (captions == null) return [];

      final renderer = captions['playerCaptionsTracklistRenderer'];
      if (renderer == null) return [];

      final trackList = renderer['captionTracks'] as List? ?? [];
      for (final track in trackList) {
        final baseUrl = track['baseUrl']?.toString() ?? '';
        if (baseUrl.isEmpty) continue;

        final langCode = track['languageCode']?.toString() ?? '';
        final name = track['name']?['simpleText']?.toString() ??
            track['name']?['runs']?.map((r) => r['text']).join() ??
            langCode;
        final kind = track['kind']?.toString() ?? '';

        tracks.add(CaptionTrack(
          languageCode: langCode,
          name: name,
          baseUrl: baseUrl,
          isAutoGenerated: kind == 'asr',
        ));
      }

      return tracks;
    } catch (e) {
      debugPrint('CaptionService.getTracks: $e');
      return [];
    }
  }

  /// Fetch and parse caption cues from a track URL.
  static Future<List<CaptionCue>> getCues(String trackUrl) async {
    try {
      final uri = Uri.parse(trackUrl);
      final res = await _http.get(uri, headers: {
        'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      }).timeout(const Duration(seconds: 10));

      if (res.statusCode != 200) return [];

      return _parseTtml(res.body);
    } catch (e) {
      debugPrint('CaptionService.getCues: $e');
      return [];
    }
  }

  /// Parse YouTube's TTML caption format.
  static List<CaptionCue> _parseTtml(String xml) {
    final cues = <CaptionCue>[];

    // Match <p begin="..." end="..." ...>text</p>
    final pattern = RegExp(
      r'<p\s+[^>]*?begin="([^"]*)"[^>]*?end="([^"]*)"[^>]*?>(.*?)</p>',
      dotAll: true,
    );

    for (final match in pattern.allMatches(xml)) {
      final beginStr = match.group(1) ?? '';
      final endStr = match.group(2) ?? '';
      var text = match.group(3) ?? '';

      // Clean HTML tags from text
      text = text.replaceAll(RegExp(r'<[^>]+>'), '');
      text = text.replaceAll('&amp;', '&');
      text = text.replaceAll('&lt;', '<');
      text = text.replaceAll('&gt;', '>');
      text = text.replaceAll('&quot;', '"');
      text = text.replaceAll('&#39;', "'");
      text = text.replaceAll('&nbsp;', ' ');
      text = text.trim();

      if (text.isEmpty) continue;

      final start = _parseTtmlTime(beginStr);
      final end = _parseTtmlTime(endStr);

      if (start != null && end != null) {
        cues.add(CaptionCue(start: start, end: end, text: text));
      }
    }

    // Also try SRT-like format: <p begin="00:00:01.000" end="00:00:04.000">text</p>
    if (cues.isEmpty) {
      final srtPattern = RegExp(
        r'<p[^>]*?begin="(\d+:\d+:\d+[\.,]\d+)"[^>]*?end="(\d+:\d+:\d+[\.,]\d+)"[^>]*?>(.*?)</p>',
        dotAll: true,
      );
      for (final match in srtPattern.allMatches(xml)) {
        var text = match.group(3) ?? '';
        text = text.replaceAll(RegExp(r'<[^>]+>'), '').trim();
        if (text.isEmpty) continue;

        final start = _parseSrtTime(match.group(1) ?? '');
        final end = _parseSrtTime(match.group(2) ?? '');

        if (start != null && end != null) {
          cues.add(CaptionCue(start: start, end: end, text: text));
        }
      }
    }

    // Sort by start time
    cues.sort((a, b) => a.start.compareTo(b.start));
    return cues;
  }

  /// Parse TTML time format (e.g., "123.456s" or "00:01:23.456").
  static Duration? _parseTtmlTime(String time) {
    if (time.isEmpty) return null;

    // Format: "123.456s"
    if (time.endsWith('s')) {
      final seconds = double.tryParse(time.substring(0, time.length - 1));
      if (seconds != null) {
        return Duration(milliseconds: (seconds * 1000).round());
      }
    }

    // Format: "00:01:23.456" or "01:23.456"
    final parts = time.split(':');
    if (parts.length == 3) {
      final h = int.tryParse(parts[0]) ?? 0;
      final m = int.tryParse(parts[1]) ?? 0;
      final secParts = parts[2].split('.');
      final s = int.tryParse(secParts[0]) ?? 0;
      final ms = secParts.length > 1
          ? (int.tryParse(secParts[1]) ?? 0)
          : 0;
      return Duration(hours: h, minutes: m, seconds: s, milliseconds: ms);
    }
    if (parts.length == 2) {
      final m = int.tryParse(parts[0]) ?? 0;
      final secParts = parts[1].split('.');
      final s = int.tryParse(secParts[0]) ?? 0;
      final ms = secParts.length > 1
          ? (int.tryParse(secParts[1]) ?? 0)
          : 0;
      return Duration(minutes: m, seconds: s, milliseconds: ms);
    }

    return null;
  }

  /// Parse SRT time format (e.g., "00:01:23,456").
  static Duration? _parseSrtTime(String time) {
    if (time.isEmpty) return null;
    final clean = time.replaceAll(',', '.');
    return _parseTtmlTime(clean);
  }

  /// Extract a JSON object from the page source by key.
  static Map<String, dynamic>? _extractJson(String body, String key) {
    final pattern = RegExp('var $key\\s*=\\s*(\\{.*?\\});', dotAll: true);
    final match = pattern.firstMatch(body);
    if (match == null) return null;
    try {
      return jsonDecode(match.group(1)!) as Map<String, dynamic>;
    } catch (_) {
      return null;
    }
  }

  static void dispose() {
    _http.close();
  }
}
